# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.setWindowModality(QtCore.Qt.ApplicationModal)
        mainwindow.resize(1371, 752)
        mainwindow.setStyleSheet("")
        mainwindow.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Tunisia))
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(1371, 711))
        self.frame.setMaximumSize(QtCore.QSize(1371, 711))
        font = QtGui.QFont()
        font.setFamily("Arabic Typesetting")
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-image: url(:/background/Image/pexels-skitterphoto-730921.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(40, 9, 40, 38)
        self.gridLayout.setHorizontalSpacing(400)
        self.gridLayout.setObjectName("gridLayout")
        self.ProsecutionOffices = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arabic Typesetting")
        font.setPointSize(22)
        self.ProsecutionOffices.setFont(font)
        self.ProsecutionOffices.setObjectName("ProsecutionOffices")
        self.gridLayout.addWidget(self.ProsecutionOffices, 0, 0, 1, 1)
        self.DeanShips = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arabic Typesetting")
        font.setPointSize(22)
        self.DeanShips.setFont(font)
        self.DeanShips.setObjectName("DeanShips")
        self.gridLayout.addWidget(self.DeanShips, 0, 1, 1, 1)
        self.farmers = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arabic Typesetting")
        font.setPointSize(22)
        self.farmers.setFont(font)
        self.farmers.setObjectName("farmers")
        self.gridLayout.addWidget(self.farmers, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arabic Typesetting")
        font.setPointSize(22)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 0, 1, 1)
        self.histroy = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arabic Typesetting")
        font.setPointSize(22)
        self.histroy.setFont(font)
        self.histroy.setObjectName("histroy")
        self.gridLayout.addWidget(self.histroy, 1, 1, 1, 1)
        self.distribution = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arabic Typesetting")
        font.setPointSize(22)
        self.distribution.setFont(font)
        self.distribution.setObjectName("distribution")
        self.gridLayout.addWidget(self.distribution, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1371, 21))
        self.menubar.setObjectName("menubar")
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "mainwindow"))
        self.ProsecutionOffices.setText(_translate("mainwindow", "النيابات"))
        self.DeanShips.setText(_translate("mainwindow", "عمادات"))
        self.farmers.setText(_translate("mainwindow", "فلاحة"))
        self.pushButton_7.setText(_translate("mainwindow", "PushButton"))
        self.histroy.setText(_translate("mainwindow", "سجل"))
        self.distribution.setText(_translate("mainwindow", "التوزيع"))
from qrc_source import source
